#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

build() {
    local tag=$1

    docker build --build-arg tag="${tag}" \
        -t "${DOCKER_REPO}:${tag}" .
}

if [[ $# -eq 0 ]]; then
    read -ra tags <"${0%/*}/tags"
    for t in "${tags[@]}"; do
        build "$t"
    done
else
    build "$@"
fi
