#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

if [[ $# -eq 0 ]]; then
    read -ra tags <"${0%/*}/tags"
    for v in "${tags[@]}"; do
        docker push "${DOCKER_REPO}:$v"
    done
else
    docker push "$@"
fi
