name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [al2, al2-rustup]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            ghcr.io/anyakichi/lambda-rust-builder
          tags: ${{ matrix.tag }}-devel
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: use_rustup=${{ matrix.tag == 'al2-rustup' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
