name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [build-provided, build-provided.al2]
    steps:
      - uses: actions/checkout@v2
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: tag=${{ matrix.tag }}
          tags: anyakichi/lambda-rust-builder:${{ matrix.tag }}
